#Datei docker-compose.yml 

    version: '3'
    services:
      nginx: 
        image: nginx:latest
        container_name: ve_production_nginx
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
          - 80:80
          - 443:443