version: '2.4'
services:
  mariadb:
    image: tobi312/rpi-mariadb:10.3
    #container_name: mariadb
    restart: unless-stopped
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      TZ: Europe/Berlin
      #MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      # OLD my-secret-pw
      MYSQL_ROOT_PASSWORD: p
      MYSQL_DATABASE: user
      MYSQL_USER: user
      MYSQL_PASSWORD: p
    ports:
      - 3306:3306
    healthcheck:
      test:  mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD || exit 1
      #test:  mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD || exit 1
      interval: 60s
      timeout: 5s
      retries: 5
      #start_period: 30s